require('options')
require('keymaps')
require('autocmds')

require('plugins.tokyonight')
require('plugins.treesitter')
require('plugins.lualine')
require('plugins.oil')
require('plugins.git_integration')
require('plugins.telescope')
require('plugins.lsp')
require('plugins.formatting')
require('plugins.completions')
require('plugins.mini')
require('plugins.copilot')
require('plugins.undotree')
